export const content = {
    who: "Founded by a young African woman in global health, Public Health Research & Impact Hub is a female-led initiative designed to bridge the gap between academic knowledge and practical health solutions across Africa — with a strong focus on maternal health equity.We exist to empower women in science and health leadership, build local research capacity, and drive African-led health innovation rooted in communities.> “This isn’t just a hub. It’s a movement — led by African women for African futures.",
    what: "At Public Health Research & Impact Hub, we empower African students, early-career researchers, and public health professionals to generate translate, and apply impactful research—especially in maternal and community health. Founded and led by a young African woman in global health, we are building a new model of research leadership: one that is grounded in local context, driven by equity, and committed to real-world solutions.",
    mission: "To amplify the role of local research — especially by young African women — in shaping maternal and public health policy, programs, and community outcomes.",
    vision: "A continent where women researchers lead, collaborate, and implement health solutions that serve every mother, every family, and every forgotten region.",
    ourValues: ["Equity:	We promote health justice across gender, geography, and systems.", "Empowerment	:We equip students, especially women, to lead and publish impactful research.", "Excellence: We prioritize rigor, relevance, and real-world translation.", "Collaboration: We partner with ministries, communities, and global allies.", "Representation:	We believe in African women leading African research agendas."],
    ourCore: [" We help undergraduate and postgraduate students strengthen their academic and professional journey.", "  We lead and support community-centered research in Sudan (Darfur), focusing on: Access to maternal health services Health system gaps and gender equity Community-based interventions and implementation science", " We translate research into impact through: Outreach programs in underserved communities Health education for women and girls Policy briefs and evidence for decision-makers"],
    why: "Why We Exist At Public Health Research & Impact Hub, our work begins with a deep sense of purpose—and a personal story. I am a public health researcher from Darfur, Sudan. I’ve seen firsthand the devastating impact that limited access to maternal health care and weak research systems have on women, mothers, and entire communities. In regions like Darfur, maternal health outcomes remain dangerously poor—not because women don’t care, but because the systems meant to protect them are under-researched, under-resourced, and overlooked. Very few studies are conducted in these fragile areas. As a result, there is no strong data to inform decisions, guide interventions, or advocate for funding. Without research, there is no voice. Without voice, there is no change. That is why this hub exists: To ensure that no woman dies giving life because no one studied her reality. To create a space where young African researchers—especially women—can lead evidence that speaks for our people. And to make sure that Darfur and other underserved regions are not just subjects of research—but sources of solutions. Because maternal health is not just a public health issue—it’s a matter of justice.",
    founder: "I’m Dr. Rogya Abdelrasol, a medical doctor and public health professional based in Kampala, Uganda, deeply passionate about advancing women’s health in Africa—especially in underserved regions—through research, advocacy, and community-driven solutions. I’m pursuing a Master’s in Public Health and plan to earn a PhD in Public Health & Policy focused on reproductive and maternal health. My journey has been shaped by resilience: I graduated medical school during Sudan’s conflict, managing bipolar disorder with strength, and recently lost both parents—my greatest supporters. This platform honors them and every girl who dares to rise. I’ve led projects with the Friedrich Ebert Foundation and Goethe-Institut, and volunteered with Al Sharq Youth Network, delivering youth and gender programs. Fluent in Arabic and English, conversational in Spanish, and with basic German, I bring cultural versatility and global curiosity. As a YouTuber and content creator, I amplify public health issues and empower African women. I believe in storytelling, collaboration, and creating hopeful spaces—let’s build something meaningful together."
}